var myArray = [
	"Cookout",
	"Chick-fil-a",
	"Hardees",
	"Salsaritas",
	"Zaxby's",
	"Marco's",
	"Massimo's",
	"Arby's",
	"Which Wich",
	"Culvers",
	"Bojangles",
	"Go Burrito",
	"Johnson's",
	"Burger King",
	"Biscuitville",
	"Cracker Barrel",
	"Olive Garden",
	"Casa Grande",
	"Mayflower",
	"Mcdonalds",
	"Sonic",
	"B-DUBS",
	"Smoke Pit",
	"Sheetz"
];